[package]
name = "orisyvra-volume"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chacha20poly1305.workspace = true
hkdf.workspace = true
hmac.workspace = true
orisyvra = { path = "../orisyvra" }
orisyvra-windows = { path = "../orisyvra-windows" }
rand.workspace = true
sha2.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
