[workspace]
members = [
    "crates/orisyvra-core",
    "crates/orisyvra",
    "crates/orisyvra-pin",
    "crates/orisyvra-analysis",
    "crates/orisyvra-gui",
    "crates/orisyvra-volume",
    "crates/orisyvra-volume-gui",
    "crates/orisyvra-windows",
]
resolver = "2"

[workspace.package]
version = "0.2.0-alpha.1"
edition = "2021"
license = "MIT"
authors = ["OrIsyVra Contributors"]
repository = "https://github.com/urotsuki-san/OrIsyVra"
rust-version = "1.81"

[workspace.dependencies]
anyhow = "1.0"
argon2 = "0.5"
base64 = "0.22"
chacha20poly1305 = { version = "0.10", features = ["std"] }
clap = { version = "4.5", features = ["derive"] }
eframe = { version = "0.31.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
font8x8 = "0.3"
hkdf = "0.12"
hmac = "0.12"
image = { version = "0.25", default-features = false, features = ["png"] }
qrcode = "0.14"
rand = "0.8"
rfd = "0.17"
rpassword = "7.3"
rqrr = "0.10"
sha2 = "0.10"
subtle = { version = "2.6", default-features = false }
tempfile = "3.12"
thiserror = "1.0"
zeroize = { version = "1.8", features = ["zeroize_derive"] }

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
